site_name: Android Dev Handbook
site_description: Structured Android development handbook
site_url: https://khodorkin-dmitrii.github.io/android-dev-handbook/

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.copy

plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Android: android/index.md
  - Compose: compose/index.md
  - Kotlin:
      - Overview: kotlin/index.md
      - Basics: kotlin/basics.md
      - Kotlin vs Java: kotlin/kotlin-vs-java.md
      - Classes & Types: kotlin/classes-and-types.md
      - Collections: kotlin/collections.md
      - Functions: kotlin/functions.md
      - Generics: kotlin/generics.md
  - Java:
      - Overview: java/index.md
      - Java Core: java/core.md
      - Java Concurrency: java/concurrency.md
      - Java Exceptions: java/exceptions.md
      - JVM / Android Runtime: java/jvm-android-runtime.md
  - Coroutines & Flow: coroutines-flow/index.md
  - Architecture: architecture/index.md
  - Fundamentals:
      - Overview: fundamentals/index.md
      - OOP: fundamentals/oop.md
      - SOLID: fundamentals/solid.md
      - Design Patterns: fundamentals/design-patterns.md
      - Algorithms & Complexity: fundamentals/algorithms-complexity.md
      - Memory & Runtime Basics: fundamentals/memory-runtime-basics.md
